spring:
  jpa:
    show-sql: true
    database-platform: com.example.jpa_sequence.SimpleMariaDB103Dialect
    hibernate:
      format_sql: true
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      continue-on-error: true